import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: '#020617',
    paddingTop:20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#e5e7eb',
    textAlign: 'center',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 13,
    color: '#9ca3af',
    textAlign: 'center',
    marginBottom: 12,
  },
  form: {
    backgroundColor: '#0f172a',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#1f2937',
    marginBottom: 10,
  },
  label: {
    fontSize: 13,
    color: '#e5e7eb',
    marginBottom: 4,
    marginTop: 8,
    fontWeight: '500',
  },
  input: {
    borderWidth: 1,
    borderColor: '#374151',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#e5e7eb',
    backgroundColor: '#1e293b',
    fontSize: 14,
  },
  button: {
    marginTop: 16,
    backgroundColor: '#22c55e',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  buttonText: {
    color: '#020617',
    fontWeight: '600',
    fontSize: 14,
  },
  testButton: {
    marginTop: 12,
    backgroundColor: 'transparent',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#374151',
  },
  testButtonText: {
    color: '#9ca3af',
    fontWeight: '500',
    fontSize: 14,
  },
  error: {
    marginTop: 8,
    color: '#f97373',
    fontSize: 13,
    fontWeight: '500',
  },
  testInfo: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#1e293b',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  testInfoText: {
    color: '#64748b',
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  logout: {
    color: '#f97316',
    fontSize: 14,
    fontWeight: '600',
  },
  empty: {
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: 40,
    fontSize: 14,
  },
});